event_app/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.event, name='event'),
    path('join-event/', views.join_event, name='join_event'),
	path('attended-event/', views.attended_event, name='attended-event'),
    path('participate/', views.participate, name='participate'),
]

form_app/urls.py
from django.conf.urls import url
from django.urls import re_path
from .views import index,add_member

urlpatterns = [
    re_path('registration/', index, name='registration'),
	re_path('add_member/', add_member, name = 'add_member')
]

ppw_tugas/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from home_app.views import signup as signup
urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include(('form_app.urls','form_app'), namespace = 'member')),
    path('', include(('home_app.urls','home_app'), namespace= 'home')),
#path('accounts/', include('form_app.urls'), namespace='accou'),
    path('events/', include(('event_app.urls','event_app'), namespace='event')),
    path('news/', include(('news_app.urls', 'news_app'), namespace='news')),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
	path('testimoni/', include('testimoni.urls')),
]

event_app/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    nama_event = models.CharField(max_length=100)
    tanggal = models.DateField()
    deskripsi = models.TextField()
    foto_event = models.TextField()


    def __str__(self):
        return self.nama_event



class Participant(models.Model):
    nama = models.CharField(max_length = 100)
    username = models.CharField(max_length=50)
    email = models.EmailField()
    event = models.CharField(max_length=100)

    def __str__(self):
        return self.nama

event_app/forms.py
from django import forms
from .models import Event

class ParticipantForm(forms.Form):

    attrs= {
        'class' : 'form-control',
    }

    name_attrs = {
        'class' : 'form-control'
    }

    email_attrs = {
        'class' : 'form-control'
    }

    nama = forms.CharField(max_length=100, required=True, widget= forms.TextInput(attrs=name_attrs))
    username = forms.CharField(required = True, max_length = 100, widget = forms.TextInput(attrs=attrs))
    event = forms.ModelChoiceField(queryset=Event.objects.all(), label='Event', widget=forms.Select)

event_app/views.py
from django.shortcuts import render
from .models import Event, Participant
from .forms import ParticipantForm
from django.http import HttpResponseRedirect
from . import forms
import json
# Create your views here.

response ={}
def event(request):
    event = Event.objects.all()
    participant = Participant.objects.all()
    response['all_event'] = event
    response['participant'] = participant
    html = 'event.html'
    return render(request, html, response)

def join_event(request):
	if not request.user.is_authenticated :
		return HttpResponseRedirect('/')
	response['join_event'] = ParticipantForm
	html = 'join-event.html'
	return render(request, html, response)
	
def attended_event(request):
	list_event = []
	list_user = Participant.objects.all()
	list_daftar_event = Event.objects.all()
	if request.user.is_authenticated:
		for i in list_user:
			if i.email == request.user.email:
				list_event.append(i)
	context = {
		'list_event' : list_event,
		'list_daftar_event' : list_daftar_event,
		'banyak_event' : len(list_event)
	}
	response = render(request, 'attended.html', context = context)
	return response


def participate(request):
	form = forms.ParticipantForm(request.POST)
	# objek_member = Event.objects.values_list('username')
	if (form.is_valid()):
		respond = HttpResponseRedirect('/events/')
		response['nama'] = request.POST['nama']
		response['username'] = request.POST['username']
		response['email'] = request.user.email
		response['event'] = form.cleaned_data['event']
		member = Participant(nama = response['nama'], username = response['username'], email = response['email'], event = response['event'])
		member.save()
		return respond
	else:
		form = forms.ParticipantForm()

	return render(request, 'event.html', response)

event_app/templates/attended.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrahead %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>    
{% endblock extrahead %}
{% block content %}
<div class="jumbotron" style="background-color:#127FB9; text-align: center">
    <h1 style="font-size : 50px"> ATTENDED EVENT </h1>
</div>
<div class = "container">
    <div class="table-responsive">
        {% if user.is_authenticated %}
            {% if list_event %}
                <h2 style="font-size : 25px;text-align: center"> Event yang pernah didaftarkan {{ user.first_name }} </h2><br>
                <h2 style="font-size : 18px;text-align: left"> Jumlah event yang dihadiri : {{ banyak_event }} </h2>
                <table class = "table table-hover">
                    <thead style="text-align: center">
                        <th> Nama </th>
                        <th> Event yang dikunjungi </th>
                        <th> Tanggal event </th>
                    </thead>
                    <tbody>
                        {% for i in list_event%} 
                        {% for j in list_daftar_event %}
                        <tr>
                            {% if i.event == j.nama_event %}   
                            <td> {{i.nama}} </td>                   
                            <td> {{i.event}} </td>
                            <td> {{j.tanggal}} </td>
                            {% endif %}
                        </tr>  
                        {% endfor %} 
                        {% endfor %}                          
                    </tbody>
                </table>
            {% else %}
                <h2 style="font-size : 30px;text-align: center"> Belum terdaftar di event apapun </h2><br>
            {% endif %}
        {% else %}
            <h2 style="font-size : 30px; text-align: center" > Belum terdaftar, silahkan log-in terlebih dahulu</h2> 
            <button type="button" style="text-align: center" class="btn btn-primary" onclick="window.location.href='/login'"> Login </button>
            <br><br>
        {% endif %}
    </div> 
</div> 
{% endblock %}

event_app/templates/event.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/event.css' %}">
{% endblock %}
{% block content %}

<div class="container-text" style="background-color:#127FB9; height:196px;">
    <p class="event-test">EVENT</p>
</div>
<div class="event-cotent">
            <h1>Kegiatan yang ada</h1>
    <div class="table-responsive all-table">
        <table class="table ">
            <thead class="thead-light">
               {% if all_event %}
            <tr>

                <th style='background-color: #00A6FF;'>Nama Event</th>
                <th style='background-color: #00A6FF;'>Gambar Event</th>
                <th style='background-color: #00A6FF;'>Tanggal</th>
                <th style='background-color: #00A6FF;'>Deskripsi</th>
                <th style='background-color: #00A6FF;'>Peserta</th>
            </tr>
            <tbody>
                {% for i in all_event %}
                <tr class="table-event">
                    <td style='background-color:#D1EEFD'>{{i.nama_event}}</td>
                    <td style='background-color:#D1EEFD'>
                        <img src="{{i.foto_event}}" style="width:200px;height:150px;">
                    </td>
                    <td style='background-color: #D1EEFD'>{{i.tanggal}}</td>
                    <td style='background-color: #D1EEFD'>{{i.deskripsi}}</td>
                    <td style='background-color:#D1EEFD'>
                    {% for j in participant %}
                    {% if j.event == i.nama_event %}
                        <p>- {{j.nama}} </p>

                    {% endif %}
                    {% endfor %}
                    <hr style="width:100%">
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            {% endif %}
        </table>
    </div>
</div>


{% endblock %}

event_app/templates/join-event.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="jumbotron" style="background-color:#127FB9; text-align: center">
    <h1 style="font-size : 50px"> JOIN EVENT </h1>
</div>
<section class="container" id="projects">
    <div class="row">
        <div class = "col-md-3">
        </div>
        <div class="col-md-6 col-md-offset-6">
            <div class="form-regis" style="left:50%;">
                <form id="form" method="POST" action="{% url 'event:participate' %}">
                    {% csrf_token %}
                    {{join_event}}
                    <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                </form>
            </div>
        </div>
    </div>
    <br>
    <button type="button" class="btn btn-info" onclick="window.location.href='/'"> Back </button><br><br>
</section>
{% endblock %}